platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'DJISDKSwiftDemo' do
   pod 'DJI-SDK-iOS', '~> 4.15.1'
   pod 'DJIWidget', '~> 1.6.5'
   pod 'DJIFlySafeDatabaseResource', '~> 01.00.01.18'
end
