platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'DJISDKSwiftDemo' do
   pod 'DJI-SDK-iOS', '~> 4.13.1'
   pod 'DJIWidget', '~> 1.6.3'
   pod 'DJIFlySafeDatabaseResource', '~> 01.00.01.17'
end
