platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'DJISDKSwiftDemo' do
   pod 'DJI-SDK-iOS', '~> 4.14-trial2'
   pod 'DJIWidget', '~> 1.6.4'
   pod 'DJIFlySafeDatabaseResource', '~> 01.00.01.17'
end
